%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.2.1

-ifndef(msg_pb).
-define(msg_pb, true).

-define(msg_pb_gpb_version, "4.2.1").

-ifndef('LOGINREQUEST_PB_H').
-define('LOGINREQUEST_PB_H', true).
-record('LoginRequest',
        {username               :: iodata(),        % = 1
         password               :: iodata()         % = 2
        }).
-endif.

-ifndef('LOGINRESPONSE_PB_H').
-define('LOGINRESPONSE_PB_H', true).
-record('LoginResponse',
        {token                  :: iodata()         % = 1
        }).
-endif.

-ifndef('SENDMESSAGEREQUEST_PB_H').
-define('SENDMESSAGEREQUEST_PB_H', true).
-record('SendMessageRequest',
        {sender                 :: iodata() | undefined, % = 1
         receiver               :: iodata() | undefined, % = 2
         text                   :: iodata() | undefined % = 3
        }).
-endif.

-ifndef('REQUEST_PB_H').
-define('REQUEST_PB_H', true).
-record('Request',
        {login                  :: msg_pb:'LoginRequest'() | undefined, % = 1
         send_message           :: msg_pb:'SendMessageRequest'() | undefined % = 2
        }).
-endif.

-endif.
